import { useState } from 'react'
import './index.css';

// type SectionColors = Record<string, string[]>;
interface FontSizeToken {
    value: string;
    section: string;
    element: string;
}



interface SpacingToken {
    value: string;
    section: string;
    property: string;
}



interface DesignTokens {
  sections: Record<string, string[]>;
  cssVars: Record<string, string>;
  fonts:{families: string[]; sizes: FontSizeToken[]};
  spacing: SpacingToken[];
  sourceUrl:string;
}



const BACKEND_URL = "http://localhost:5000/extractor";

function buildFontSizeKey(s:FontSizeToken) : string {
   const sectionShort : Record<string, string> = {
    'Navigation' : 'nav',
    'Header/ Hero': 'hero',
    "Main Content": 'body',
    'Footer': 'footer',
    'Components': 'ui',
    "Sidebar": 'sidebar'
   };

  //  const elementName: Record<string, string> = {
  //   'h1' : 'title',
  //   'h2': 'heading',
  //   'h3': 'subheading',
  //   'h4': 'subheading',
  //   'p': 'text',
  //   'span': 'label',
  //   'a': 'link',
  //   'button': 'btn',
  //   'li': 'list',
  //    'label': 'label',
  //  };

   const section = sectionShort[s.section] || 'text';
    // const element = elementName[s.element] || s.element;
    // return `${section}-${element}`;

    
    
    // 🧠 1. Convert the string value (e.g., "48px") into a pure mathematical number (48)
    const numericSize = parseFloat(s.value);

    // 🧠 2. Run the size-range evaluator to build consistent typographic token keys
    let structuralRole = 'body-base';

    if (numericSize >= 56)       structuralRole = 'display-xl';  // Huge feature titles
    else if (numericSize >= 40)  structuralRole = 'display-lg';  // Main layout headers
    else if (numericSize >= 32)  structuralRole = 'heading-xl';  // Content section headers
    else if (numericSize >= 24)  structuralRole = 'heading-lg';  // Article titles
    else if (numericSize >= 20)  structuralRole = 'heading-md';  // Card titles or subtitles
    else if (numericSize >= 16)  structuralRole = 'body-base';   // Standard reading/paragraph text
    else if (numericSize >= 14)  structuralRole = 'body-sm';     // Secondary labels or navigation links
    else                         structuralRole = 'caption';     // Fine print, timestamps, and footers

    // 🧠 3. Combine them to generate clear configuration utility keys
    return `${section}-${structuralRole}`;


}



function buildSpacingKey(s: SpacingToken): string {
  const sectionShort: Record<string, string> ={
     'Navigation': 'nav',
     'Header/ Hero': 'hero',
     'Main Content': 'body',
     'Components': 'ui',
     'Sidebar': 'sidebar',
  };

  const section = sectionShort[s.section] || 'layout';
  return `${section}-${s.property}`;
}



// function generateTailwindConfig(tokens: DesignTokens): string {

//   // Flattern all section colors, duplicates

//     const fontSizeLines = tokens.fonts.sizes.length > 0 ? tokens.fonts.sizes
//        .map(s =>{
//           const key = buildFontSizeKey(s);
//           const rem = (parseFloat(s.value)/16).toFixed(3);
//          return `        '${key}': ['${rem}rem', { lineHeight: '1.5' }], /* ${s.value} — ${s.section} <${s.element}> */`;
//             })
//             .join('\n')
//         : '';

//     const spacingLines = tokens.spacing.length > 0 ? tokens.spacing 
//         .map(s => {
//             const key = buildSpacingKey(s);
//             const rem = (parseFloat(s.value) / 16).toFixed(3);
//            return `        '${key}': '${rem}rem', /* ${s.value} — ${s.section} ${s.property} */`;
//             })
//             .join('\n')
//         : '';

//   const sectionColorLines = Object.entries(tokens.sections)
//     .map(([sectionName, colors]: [string, string[]]) =>{
//       const sectionKey = sectionName
//         .toLowerCase()
//         .replace(/[^a-z0-9]+/g, '-')
//         .replace(/^-|-$/g, '');

//         const colorEnteries = colors
//           .map((hex: string, i: number) => `        '${sectionKey}-${i + 1}': '${hex}'`)
//                 .join(',\n');

//             return colorEnteries;
//     })
//     .filter(Boolean)
//     .join(',\n');

//     // CSS variables
//      const cssVarLines = Object.entries(tokens.cssVars)
//        .map(([varName, val]) =>{
//          const key = varName.replace('--', '');
//           return `        '${key}': '${val}'`;
//        })
//         .join(',\n');


//   // Build color enteries
//   const allColorLines = [sectionColorLines, cssVarLines]
//     .filter(Boolean)
//     .join(',\n');

//     const fontFamilyLines = tokens.fonts.families
//         .map((f, i) => `        'site-${i + 1}': ['${f}', 'sans-serif']`)
//         .join(',\n');

   

//  return `/** @type {import('tailwindcss').Config} */
// /** Auto-generated by Tailwind Config Extractor */
// /** Source: ${tokens.sourceUrl} */
// /**
//  * HOW TO USE THIS FILE:
//  * 1. Copy this file to the root of your project
//  * 2. Make sure Tailwind CSS is installed
//  * 3. Use colors as utility classes:
//  *
//  *    Navigation:   bg-navigation-1, text-navigation-2
//  *    Hero/Header:  bg-header-hero-1
//  *    Main content: bg-main-content-1
//  *    Footer:       bg-footer-1, text-footer-2
//  */


// module.exports = {
//   theme: {
//     extend: {
//       colors: {
// ${allColorLines}
//       },
//       fontFamily :{
//         ${fontFamilyLines}
//       },  
//       fontSize:{
//        ${fontSizeLines}
//       },
//       spacing:{
//        ${spacingLines}
//       },
//     },
//   },
//   plugins: [],
// };
// `;
// }

//  Download Config  - browser file download 

// function downloadConfig(tokens: DesignTokens) {
//   const content = generateTailwindConfig(tokens);
//   const blob = new Blob([content], { type: 'text/javascript' });
//   const url = URL.createObjectURL(blob);
//   const a = document.createElement('a');
//   a.href = url;
//   a.download = 'tailwind.config.js';
//   a.click();
//   URL.revokeObjectURL(url);
// }




//  CopytoclipBoard feeature 

async function getAuthTokenFromDashboard(): Promise<string | null> {
  try {
     // Queries your running local dashboard tab
    //  const tabs = await chrome.tabs.query({ url: ["http://localhost:5173/*", "http://localhost:5174/*"  ]}); 
    //  if (!tabs || tabs.length === 0) return null;

     const allTabs = await chrome.tabs.query({});

     const dashboardTabs = allTabs.filter(tab => 
      tab.url && (tab.url.includes("localhost:5173") || tab.url.includes("localhost:5174"))
    );

    if (dashboardTabs.length === 0) {
      console.warn("⚠️ No active localhost dashboard tabs were detected open in this browser window.");
      return null;
    }
     

  // for (const tab of tabs) {
  //   if (!tab.id) continue;

     for (const tab of dashboardTabs) {
      if (!tab.id) continue;
         
    try {
     // Securely extracts the token you saved during login
     const result = await chrome.scripting.executeScript({
      //  target: { tabId: tabs[0].id! },
      target: { tabId: tab.id },
       func: () => localStorage.getItem('token'), 
     });

    //  return result[0]?.result as string || null;

       const token = result[0]?.result as string || null;
             
             // If this specific tab contains a valid token, return it immediately!
             if (token) {
                 console.log(`✅ Session passport found in Tab ID: ${tab.id}`);
                 return token;
             }
         } catch (scriptErr) {
             // Silently skip any tabs that are still loading or restricted
             console.warn(`Skipping tab ${tab.id}:`, scriptErr);
         }
     }

     return null;


  } catch (err) {
     console.error("Failed to read token from dashboard:", err);
     return null;
  }
}


async function copyToClipboard(text: string) {
  try {
    await navigator.clipboard.writeText(text);
  } catch (e) {
    const el = document.createElement('textarea');
    el.value = text;
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
  }
}


function App() {

  const [hashScanned, setHashScanned] = useState(false);

  const [tokens, setToken] = useState<DesignTokens | null>(null);

  const [isScanning, setIsScanning] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const [copiedColor, setCopiedColor] = useState<string | null>(null);




  // const pingWebpageDom = async () => {
  //   // fetch the active Browser window tab identity
  //   const [activeTab] = await chrome.tabs.query({ active: true, currentWindow: true });

  //   if (!activeTab || !activeTab.id) {
  //     return;
  //   }

  //   chrome.tabs.sendMessage(activeTab.id, { action: "PING_DOM" }, (response) => {

  //     if (response && response.status === "success") {
  //       setSectionedColors(response.sections);
  //        setHashScanned(true);
  //     }
  //   });
  // }


  const pingWebpageDom = async () => {
    setIsScanning(true);
    const [activeTab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (!activeTab?.id) { setIsScanning(false); return; }

     const sourceUrl = activeTab.url ? new URL(activeTab.url).hostname : 'unknown';


    chrome.tabs.sendMessage(activeTab.id, { action: "PING_DOM" }, (response) => {
      if (response?.status === "success") {
        setToken({
          sections: response.sections,
          cssVars: response.cssVars,
          fonts: response.fonts,
          spacing:response.spacing,
          sourceUrl,

        });
        setHashScanned(true);
      }
      setIsScanning(false);
    });
  };

  // downliad config File Api integration
    const handleDownloadConfig = async ()=>{
       if(!tokens) return;

       try{
          const colorsFlattened = [...new Set(Object.values(tokens.sections).flatMap(c => c))];
          const fontsFlattened = tokens.fonts.families;

          const fontsizeMapped = tokens.fonts.sizes.map(s => [buildFontSizeKey(s), `${(parseFloat(s.value)/16).toFixed(3)}rem`]);
          const spacingMapped = tokens.spacing.map(s =>[buildSpacingKey(s), `${(parseFloat(s.value)/16).toFixed(3)}rem`]);

          const sectionsPayload: Record<string, {colors: string[]}> = {};
          Object.keys(tokens.sections).forEach((sectionName) =>{
              sectionsPayload[sectionName] ={
                colors: tokens.sections[sectionName] || []
              };
          });

          const payload = {
            colors: colorsFlattened,
            fonts: fontsFlattened,
            // fontSize: Object.fromEntries(fontsizeMapped),
            // spacing: Object.fromEntries(spacingMapped)
             fontSize:fontsizeMapped,
             spacing:spacingMapped,
             sections: sectionsPayload
          };

          const response = await fetch(`${BACKEND_URL}/extract`,{
             method:'POST',
             headers:{'Content-Type': 'application/json'},
             body: JSON.stringify(payload),
          });

          const result = await response.json();
           if(result.success){
            const blob = new Blob([result.configFileContent], {type: 'text/javascript'});
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download ='tailwind.config.js';
            a.click();
            URL.revokeObjectURL(url);
           } else{
            alert(`Extraction failed: ${result.message}`);

           }

       }catch(err){
        console.error("Backend copiler network failure:", err);
        alert("Failed to establish link to local utility backend");
       }

    };


    const handleSavetoCloud = async() =>{
       
      if(!tokens) return ;
      setIsSaving(true);

      try{

          const sessionToken = await getAuthTokenFromDashboard();

           // 🌟 SECURITY GUARD: If no token is found, stop the request and alert the user
            if (!sessionToken) {
              // alert("Cloud Save Failed: No active login session found. Please open your Web Dashboard tab, log in, and try again!");

              alert("Authentication Required: Opening your Creator Vault dashboard. Please log in or sign up, then try saving again!");
            
                if (typeof chrome !== 'undefined' && chrome.tabs) {
                    // Automatically opens the login panel tab for the user!
                    // Change the port to match whichever one your Vite application is using right now
                    chrome.tabs.create({ url: "http://localhost:5173/login" }); 
                }
              setIsSaving(false);
              return;
            }

        const  formattedSections : Record<string, any>  = {};
         Object.keys(tokens.sections).forEach((sectionName)=>{
          const cleanName = sectionName.toLowerCase().replace(/[^a-z0-9]+/g, '-') .replace(/^-|-$/g, '');
          const SectionColors =tokens.sections[sectionName] || [];

          const sectionFonts = tokens.fonts.sizes
          .filter(s => s.section === sectionName)
          .map(s => s.value);

          const sectionSpace = tokens.spacing
          .filter( s => s.section === sectionName)
          .map(s => s.value);

          formattedSections[cleanName] ={
            colors: SectionColors,
            fonts: sectionFonts,
            spaces: sectionSpace
          }

         });
         const response = await fetch(`${BACKEND_URL}/save`,{
          
             method:'POST',
             headers:{
              'Content-Type': 'application/json',
               'Authorization': `Bearer ${sessionToken}`
            },
             body: JSON.stringify({
               siteUrl: tokens.sourceUrl || "Unknown Target Site",
               siteName: (tokens.sourceUrl || "Unnamed Site") + " Theme Workspace",
               sections: formattedSections
             }),
            
         });

         if (!response.ok) {
            const errorHtml = await response.text();
            console.error("🚨 CRITICAL BACKEND STACK TRACE:\n", errorHtml);
            
            // Try to extract just the error message text from the Express HTML template
            const match = errorHtml.match(/<pre>([\s\S]*?)<\/pre>/);
            const cleanError = match ? match[1] : "Internal Server Error";
            
            alert(`Server Crash (${response.status}):\n${cleanError.split('<br>')[0]}`);
            setIsSaving(false);
            return;
          }

          const result  = await response.json();

          if(result.success){
            alert("Awesome! Design system successfully synced to your clou dashboar workspace.");
          } else{
            alert(`Cloud save failed: ${result.message}`);
          }
        
      }catch(err:any){
        console.error("Cloud vault connection issue:", err.message);
        alert("Failed to establish a network link to the clouud gateway");
      } finally {
         setIsSaving(false);
      }
    }

  const handleColorCopy = async (color: string) => {
    await copyToClipboard(color);
    setCopiedColor(color);
    setTimeout(() => setCopiedColor(null), 1500);
  };

  return (
    <div className="h-[600px] w-[360px] flex flex-col bg-slate-900 text-slate-100 font-sans antialiased overflow-hidden">

      {/* ── Header — */}
      <div className="flex-shrink-0 border-b border-slate-800 px-5 py-3">
        <h1 className="text-xl font-bold text-teal-400">Tailwind Extractor</h1>
        <p className="text-[11px] text-slate-500">Scan any site → export tailwind.config.js</p>
      </div>

      {/* Button */}
      <div className="flex-shrink-0 px-5 pt-4 pb-2 space-y-2">
        <button
          onClick={pingWebpageDom}
          disabled={isScanning}
          className="w-full bg-teal-500 hover:bg-teal-600 disabled:bg-teal-800 disabled:cursor-not-allowed text-slate-950 font-bold text-xs py-3 px-4 rounded shadow transition-all duration-200 uppercase tracking-wider"
        >
          {isScanning ? 'Scanning...' : 'Scan Page Tokens'}
        </button>

        {/* ADDED: Download button — only appears after scanning */}
        {hashScanned && tokens && (
          <div className='grid grid-cols-2 gap-2'>
          <button
            onClick={handleDownloadConfig}
            className="w-full bg-violet-600 hover:bg-violet-700 text-white font-bold text-xs py-3 px-4 rounded shadow transition-all duration-200 uppercase tracking-wider"
          >
            ↓ Download tailwind.config.js
          </button>
           <button
            onClick ={handleSavetoCloud}
            disabled={isSaving}
            className='w-full bg-emerald-600 hover: bg-emerald-700 disabled:bg-emerald-900 text-white font-bold text-[10px] py-2.5 px-2 rounded shadow transition-all duration-200 uppercase tracking-wider'
           >
            {isSaving ? 'Saving...': '☁ Save to Cloud'}
           </button>
          </div>
        )}
      </div>

    <div className="flex-1 overflow-y-auto px-5 pb-5 space-y-4">

      {/* Empty state — before first scan */}
                {!hashScanned && (
                    <div className="text-center text-xs text-slate-500 p-8 border border-dashed border-slate-800 rounded mt-4">
                        Click scan above to extract design tokens section by section
                    </div>
                )}

                {/* No colors found state */}
                {hashScanned && tokens && Object.keys(tokens.sections).length === 0 && (
                    <div className="text-center text-xs text-slate-500 p-8 border border-dashed border-slate-800 rounded mt-4">
                        No unique colors detected. Try a different page.
                    </div>
                )}
      {hashScanned && tokens && Object.keys(tokens.sections).length > 0 && (
        <div className="space-y-4 pt-2">

          {Object.entries(tokens.sections).map(([sectionName, colors]) => (
            <div key={sectionName} className="p-3 bg-slate-800 rounded border border-slate-700 space-y-2.5">

              {/*  Section header label */}
              <div className="flex items-center justify-between border-b border-slate-700/60 pb-1">
                <span className="text-[10px] font-bold text-teal-400 uppercase tracking-wider">
                  {sectionName}
                </span>
                <span className="text-[9px] bg-slate-950 px-1.5 py-0.5 rounded-full font-mono text-slate-400">
                  {colors.length} tokens
                </span>
              </div>
              <div className="grid grid-cols-3 gap-2">
                {colors.map((color) => (
                  <button
                    key={color}
                    onClick={() => handleColorCopy(color)}
                    className="flex flex-col items-center p-1.5 bg-slate-950 rounded border border-slate-900 space-y-1 hover:border-teal-500/50 transition-colors cursor-pointer w-full"
                  >
                    <div
                      className="w-full h-6 rounded"
                      style={{ backgroundColor: color }}
                    />
                    <code className="text-[9px] text-emerald-400 font-mono font-bold">
                      {copiedColor === color ? '✓ copied' : color}
                    </code>
                  </button>
                ))}
              </div>
            </div>
          ))}

          {/* css variables card */}
          {Object.keys(tokens.cssVars).length > 0 && (
            <div className="p-3 bg-slate-800 rounded border border-slate-700 space-y-2">
              <span className="text-[10px] font-bold text-violet-400 uppercase tracking-wider block">
                CSS Variables (:root)
              </span>
              <div className="grid grid-cols-3 gap-2">
                {Object.entries(tokens.cssVars).slice(0, 9).map(([varName, val]) => (
                  <button
                    key={varName}
                    onClick={() => handleColorCopy(val)}
                    className="flex flex-col items-center p-1.5 bg-slate-950 rounded border border-slate-900 space-y-1 hover:border-violet-500/50 transition-colors w-full"
                  >
                    <div className="w-full h-6 rounded" style={{ backgroundColor: val }} />
                    <code className="text-[8px] text-violet-400 font-mono truncate w-full text-center">
                      {varName}
                    </code>
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* font card  */}

          {tokens.fonts.families.length > 0 && (
            <div className = "p-3 bg-slate-800 rounded border border-slate-700 space-y-2">
               <span className='text-[10px] font-bold text-amber-400 uppercase tracking-wide block'>
                  fonts Detected
               </span>

               {/* font family name  */}
               <div className = "flex flex-wrap gap-1.5">
                  {tokens.fonts.families.map(f =>(
                    <span
                      key={f}
                      className ="text-[10px] bg-slate-950 text-amber-300 px-2 py-1 rounded font mono border border-slate-700"
                      >
                        {f}
                      </span>
                  ))}
               </div>

               {/* font size scale pills */}
               {tokens.fonts.sizes.length > 0 && (
                <div className ="space-y-1">
                  <span className ="text-[9px] text-slate-500 uppercase tracking-wider block">
                     Size Scale
                  </span>
                  {tokens.fonts.sizes.map(s =>(
                    <div
                     key={s.value}
                     className="flex items-center gap-2 bg-slate-950 rounded px-2">

                       <code className="text-[9px] text-amber-300 font-mono w-8 flex-shrink-0">
                           {s.value}
                        </code>

                        <span className ="text-slate-700">|</span>

                      <div className="flex flwx-col">
                        <span className ="text-[8px] text-teal-400 leading-tight">
                          {s.section}
                          </span>
                          <span className="text-[7px] text-slate-500 leading-tight">
                            &lt;{s.element}&gt; tag
                          </span>
                      </div>
                  </div>
                  ))}
               </div>
                )}
            </div>
          )}

          {/* spacing card  */}
           {tokens.spacing.length > 0 && (
            <div className = "p-3 bg-slate-800 rounded border border-slate-700 space-y-2">
               <span className = "text-[10px] font-bold text-sky-400 uppercase tracking-wider block">
                 Spacing Scale
               </span>
               <div className="space-y-1">
                   {tokens.spacing.map(s => {
                       const rem = (parseFloat(s.value)/16).toFixed(2);
                       return(
                         <div 
                         key={s.value}
                         className="flex items-center gap-2 bg-slate-950 rounded px-2 py-1.5 border border-slate-700/50"
                         >
                          <code className ="text-[9px]text-sky-400 font-mono w-8 flex-shrink-0">
                            {s.value}

                          </code>
                          <code className="text-[9px] text-slate-500 font-mono w-10 flex-shrink-0">
                            {rem}rem
                          </code>
                        
                           <span className="text-slate-700">│</span>

                          <span className ={`text-[8px] px-1 py-0.5 rounded font-mono flex-shrink-0 ${
                               s.property === 'gap'
                                 ? 'bg-violet-900/50 text-violet-400 border border-violet-700/50'
                                 : 'bg-sky-900/50 text-sky-400 border border-sky-700/50'
                          }`}>
                            {s.property}
                          </span>
  
                            <span className="text-slate-700">│</span>

                           <span className="text-[8px] text-teal-400 truncate">
                            {s.section}
                          </span>
                          </div>
                       );               
                    })}
                </div>  
            </div>
           )}

        </div>
      )}

    </div>

     </div>
  );
}

  export default App ;
      
