import{Request, Response} from 'express';

export const extractTailwindConfig = async(req:Request, res: Response): Promise<void> =>{
    try{
        const {colors, fonts, fontSize, spacing} = req.body;

        if(!colors || !fonts || !fontSize || !spacing){
            res.status(400).json({
                success:false,
                message:"Missing extraction parameters. colors, fonts, fontsize, and spacing are all required"
            });
            return;
        }

        const uniqueFontSizes: Record<string, string> ={};
        fontSize.forEach((item: any, idx: number) => {
            const baseKey = item.key.replace(/\s+g/g,'-').toLowerCase();
            const uniqueKey = uniqueFontSizes[baseKey]? `${baseKey}-${idx + 1}` : baseKey;
            uniqueFontSizes[uniqueKey] = item.value;
        });

         const uniqueSpacing :Record<string, string>={};
         spacing.forEach((item: any, idx: number)=>{

            let cleanKey = item.key
            .replace(/-\$\s*\{s*s\.property\s*\}/g, '')
            .replace(/\s+/g, '')
            .toLowerCase()
            .trim();

            if(!cleanKey || cleanKey === '-'){
                cleanKey = 'space-token';
            }

            const finalKey = `${cleanKey}-${idx + 1}`;
            uniqueSpacing[finalKey] = item.value;

         });

         const generatedFileText = `/** @type {import(taiwindcss).Config} */
         /** Auto-generated by Tailwind Config Extractor */
         
         module.exports = {
           theme:{
            extend: {
              colors: {
                 ${colors.map((color: string, idx: number) => `'color-token-${idx + 1}': '${color}'`).join(',\n        ')}
              },
              fontFamily: {
                 ${fonts.map((font: string, idx: number) => `'site-${idx + 1}': ['${font}', 'sans-serif']`).join(',\n        ')}
              },
              fontSize: {
                 ${Object.entries(uniqueFontSizes).map(([key, val]) => `'${key}': ['${val}', { lineHeight: '1.5' }]`).join(',\n        ')}
               },
               spacing: {
                 ${Object.entries(uniqueSpacing).map(([key, val]) => `'${key}': '${val}'`).join(',\n        ')}
                },
            }
          }
         
         },
         plugins:[],

        };`;

        res.status(200).json({
             success: true, 
             message:"Tailwind Configuration file cleaned and generated successfully.",
             configFileContent: generatedFileText.trim()
        });
    } catch (err: any){
        console.error("Extractor engine exception:", err.message);
        res.status(500).json({
            success: false,
            message:"Internal server Error while building configuration file."
        });
    }
};