import{Request, Response} from 'express';
import { Theme } from '../models/scan';
import mongoose from 'mongoose';
import { AuthenticationRequest } from '../middleware/authMiddleware';

export const extractTailwindConfig = async(req:Request, res: Response): Promise<void> =>{
    try{
        const {colors, fonts, fontSize, spacing, sections} = req.body;

        if(!colors || !fonts || !fontSize || !spacing){
            res.status(400).json({
                success:false,
                message:"Missing extraction parameters. colors, fonts, fontsize, and spacing are all required"
            });
            return;
        }
        let colorLines = '';
        if(sections && Object.keys(sections).length > 0){
            colorLines = Object.entries(sections)
            .map(([sectionName, sectionData]:[string, any]) =>{
                const sectionColors = sectionData.colors || [];
                if(sectionColors.length === 0) return '';

                const sectionKey = sectionName.toLowerCase().replace(/[^a-z0-9]+/g, '-');

                const mappedSectionColors = sectionColors.map((color:string, idx: number) =>
                     `'${sectionKey}-${idx + 1}': '${color}'`
                ).join(',\n        ');
               
                return `/* ${sectionName} Colors */\n        ${mappedSectionColors}`;
            })
            .filter(Boolean)
            .join(',\n\n        ');
        }else{
            colorLines = colors.map((color: string, idx: number)=> `'color-token-${idx + 1}': '${color}'`).join(',\n        ');
        }
        
        //  Process font Sizes
        const uniqueFontSizes: Record<string, string> ={};
        fontSize.forEach(([key, value]: [string, string], idx: number) => {
            if(!key) return ;
            const baseKey = key.replace(/\s+g/g,'-').toLowerCase();
            const uniqueKey = uniqueFontSizes[baseKey]? `${baseKey}-${idx + 1}` : baseKey;
            uniqueFontSizes[uniqueKey] = value;
        });
          
        // Process spacing
         const uniqueSpacing :Record<string, string>={};
         spacing.forEach(([key, value]:[string, string], idx: number)=>{

            if(!key) return;

            let cleanKey = key
            .replace(/-\$\s*\{s*s\.property\s*\}/g, '')
            .replace(/\s+/g, '')
            .toLowerCase()
            .trim();

            if(!cleanKey || cleanKey === '-'){
                cleanKey = 'space-token';
            }

            const finalKey = `${cleanKey}-${idx + 1}`;
            uniqueSpacing[finalKey] = value;

         });

        //  Generate Configuratrion String with section-grouped colors
         const generatedFileText = `/** @type {import('tailwindcss').Config} */
         /** Auto-generated by Tailwind Config Extractor */
         
         module.exports = {
           theme:{
            extend: {
              colors: {
                 ${colorLines}
              },
              fontFamily: {
                 ${fonts.map((font: string, idx: number) => `'site-${idx + 1}': ['${font}', 'sans-serif']`).join(',\n        ')}
              },
              fontSize: {
                 ${Object.entries(uniqueFontSizes).map(([key, val]) => `'${key}': ['${val}', { lineHeight: '1.5' }]`).join(',\n        ')}
               },
               spacing: {
                 ${Object.entries(uniqueSpacing).map(([key, val]) => `'${key}': '${val}'`).join(',\n        ')}
                },
            }
          }
         
         },
         plugins:[],

        };`;

        res.status(200).json({
             success: true, 
             message:"Tailwind Configuration file cleaned and generated successfully.",
             configFileContent: generatedFileText.trim()
        });
    } catch (err: any){
        console.error("Extractor engine exception:", err.message);
        res.status(500).json({
            success: false,
            message:"Internal server Error while building configuration file."
        });
    }
};

export const saveTailwindConfig = async (req: Request, res:Response):Promise<void> =>{
    try{
        const {siteUrl, siteName, sections} = req.body;

        if(!siteUrl || !sections){
            res.status(400).json({
                success: false,
                message: "Missing saving paraeters. siteUrl and sections object data are required"
            });
            return;
        }

        // const authUser = (req as any).user;
        // if(!authUser || !authUser._id){
        //     res.status(401).json({
        //         success:false,
        //         message: "Unauthorized access. Please log in to save configuration to your account"
        //     });
        //     return;
        // }

        // const targetUserId = new mongoose.Types.ObjectId("60d5ec8587123456789abcde");

        const authReq = req as AuthenticationRequest;
        if (!authReq.user || !authReq.user._id) {
            res.status(401).json({
                success: false,
                message: "Unauthorized access. Please log in to save configurations to your account."
            });
            return;

        }

        const targetUserId = authReq.user?._id;

        const newThemeRecord = new Theme({
            userId: targetUserId,
            siteUrl,
            siteName:siteName || "Unnamed Extracted Site",
            sections
        });

        await newThemeRecord.save();

        res.status(201).json({
            success:true,
            message: "design configuration saved to your cloud history dashboard successfully!",
            data: newThemeRecord
        });

    } catch(err: any) {
        console.error("Save controller error:", err.message);
        res.status(500).json({
            success:false,
            message:"Internal Server Error while saving configuration profile to the cloud."
        });
    }
}

export const getUserThemes = async(req: Request, res: Response): Promise<void> =>{
    try{
        // const targetUserId = new mongoose.Types.ObjectId("60d5ec8587123456789abcde");

        // const targetUserId = "60d5ec8587123456789abcde";

        const authReq = req as AuthenticationRequest;
        
         
         if (!authReq.user) {
            res.status(401).json({
                success: false,
                message: "Unauthorized access: Active user context session profile missing."
            });
            return;
        }

        const targetUserId = authReq.user?._id;

        const page = parseInt(authReq.query.page as string) || 1;
        const limit = parseInt(authReq.query.limit as string) || 6;

        const skipOffset = (page - 1) * limit;

        // const userSavedThemes = await Theme.find({userId: targetUserId}). sort({createdAt: -1});

        const [userSavedThemes, totalItemsCount] = await Promise.all([
            Theme.find({ userId: targetUserId })
                .sort({ createdAt: -1 })
                .skip(skipOffset)
                .limit(limit),
            Theme.countDocuments({ userId: targetUserId })
        ]);

         const totalPagesCount = Math.ceil(totalItemsCount / limit);



       res.status(200).json({
            success: true,
            message: "Saved configuration history workspace fetched successfully!",
            pagination: {
                totalItems: totalItemsCount,
                totalPages: totalPagesCount,
                currentPage: page,
                limit: limit,
                hasNextPage: page < totalPagesCount,
                hasPrevPage: page > 1
            },
            data: userSavedThemes
        });
        
    }catch(err: any){
        console.error("fetch history controler error", err.message);
        res.status(500).json({
            success: false,
            message:"Internal Server Error while retrieving configuration workspace history data profiles."
        });
    }
};

export const deleteHistoryConfig = async(req: Request, res:Response) : Promise<void> =>{
      try{
        const authReq = req as AuthenticationRequest;

        const configId = authReq.params.id;
        const currentUserId = authReq.user?.id;

        if(!currentUserId){
            res.status(401).json({success: false, message: "Unauthorized account session context."})
            return ;

        }

        const deleteRecord = await Theme.findOneAndDelete({
            _id: configId,
            userId: currentUserId
        });

        if(!deleteRecord){
            res.status(404).json({
                success: false,
                message: "record not found or unauthorized delete operation attemped."
            });
             return;
        }

         res.status(200).json({
            success: true,
            message:"Configuration layout completely cleared fromour cloud library."

         });


      } catch(err: any){
        console.error("Delete controller error:", err.meesage);
        res.status(500).json({success: false, message:"Internal server deleting configuration."});
      }
}