import { useState } from 'react'
import './index.css';

// type SectionColors = Record<string, string[]>;
interface DesignTokens {
  sections: Record<string, string[]>;
  cssVars: Record<string, string>;
  fonts:{families: string[]; sizes: string[]};
  spacing: string[];
  sourceUrl:string;
}




function generateTailwindConfig(tokens: DesignTokens): string {

  // Flattern all secion colors, duplicates
  const sectionColorLines = Object.entries(tokens.sections)
    .map(([sectionName, colors]: [string, string[]]) =>{
      const sectionKey = sectionName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '');

        const colorEnteries = colors
          .map((hex: string, i: number) => `        '${sectionKey}-${i + 1}': '${hex}'`)
                .join(',\n');

            return colorEnteries;
    })
    .filter(Boolean)
    .join(',\n');

    // CSS variables
     const cssVarLines = Object.entries(tokens.cssVars)
       .map(([varName, val]) =>{
         const key = varName.replace('--', '');
          return `        '${key}': '${val}'`;
       })
        .join(',\n');


  // Build color enteries
  const allColorLines = [sectionColorLines, cssVarLines]
    .filter(Boolean)
    .join(',\n');

    const fontFamilyLines = tokens.fonts.families
        .map((f, i) => `        'site-${i + 1}': ['${f}', 'sans-serif']`)
        .join(',\n');

     const fontSizeLines = tokens.fonts.sizes
        .map(s => `        '${s}': ['${(parseFloat(s) / 16).toFixed(3)}rem', { lineHeight: '1.5' }]`)
        .join(',\n');
      
    const spacingLines = tokens.spacing
        .map(s => `        '${s}': '${(parseFloat(s) / 16).toFixed(3)}rem'`)
        .join(',\n');

 return `/** @type {import('tailwindcss').Config} */
/** Auto-generated by Tailwind Config Extractor */
/** Source: ${tokens.sourceUrl} */
/**
 * HOW TO USE THIS FILE:
 * 1. Copy this file to the root of your project
 * 2. Make sure Tailwind CSS is installed
 * 3. Use colors as utility classes:
 *
 *    Navigation:   bg-navigation-1, text-navigation-2
 *    Hero/Header:  bg-header-hero-1
 *    Main content: bg-main-content-1
 *    Footer:       bg-footer-1, text-footer-2
 */


module.exports = {
  theme: {
    extend: {
      colors: {
${allColorLines}
      },
      fontFamily :{
        ${fontFamilyLines}
      },
      spacing:{
       ${spacingLines}
      },
    },
  },
  plugins: [],
};
`;
}

//  Download Config  - browser file download 

function downloadConfig(tokens: DesignTokens) {
  const content = generateTailwindConfig(tokens);
  const blob = new Blob([content], { type: 'text/javascript' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'tailwind.config.js';
  a.click();
  URL.revokeObjectURL(url);
}

//  CopytoclipBoard feeature 
async function copyToClipboard(text: string) {
  try {
    await navigator.clipboard.writeText(text);
  } catch (e) {
    const el = document.createElement('textarea');
    el.value = text;
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
  }
}


function App() {

  const [hashScanned, setHashScanned] = useState(false);

  const [tokens, setToken] = useState<DesignTokens | null>(null);

  const [isScanning, setIsScanning] = useState(false);

  const [copiedColor, setCopiedColor] = useState<string | null>(null);




  // const pingWebpageDom = async () => {
  //   // fetch the active Browser window tab identity
  //   const [activeTab] = await chrome.tabs.query({ active: true, currentWindow: true });

  //   if (!activeTab || !activeTab.id) {
  //     return;
  //   }

  //   chrome.tabs.sendMessage(activeTab.id, { action: "PING_DOM" }, (response) => {

  //     if (response && response.status === "success") {
  //       setSectionedColors(response.sections);
  //        setHashScanned(true);
  //     }
  //   });
  // }


  const pingWebpageDom = async () => {
    setIsScanning(true);
    const [activeTab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (!activeTab?.id) { setIsScanning(false); return; }

     const sourceUrl = activeTab.url ? new URL(activeTab.url).hostname : 'unknown';


    chrome.tabs.sendMessage(activeTab.id, { action: "PING_DOM" }, (response) => {
      if (response?.status === "success") {
        setToken({
          sections: response.sections,
          cssVars: response.cssVars,
          fonts: response.fonts,
          spacing:response.spacing,
          sourceUrl,

        });
        setHashScanned(true);
      }
      setIsScanning(false);
    });
  };

  const handleColorCopy = async (color: string) => {
    await copyToClipboard(color);
    setCopiedColor(color);
    setTimeout(() => setCopiedColor(null), 1500);
  };

  return (
    <div className="h-[600px] w-[360px] flex flex-col bg-slate-900 text-slate-100 font-sans antialiased overflow-hidden">

      {/* ── Header — */}
      <div className="flex-shrink-0 border-b border-slate-800 px-5 py-3">
        <h1 className="text-xl font-bold text-teal-400">Tailwind Extractor</h1>
        <p className="text-[11px] text-slate-500">Scan any site → export tailwind.config.js</p>
      </div>
      <div className="flex-shrink-0 px-5 pt-4 pb-2 space-y-2">
        <button
          onClick={pingWebpageDom}
          disabled={isScanning}
          className="w-full bg-teal-500 hover:bg-teal-600 disabled:bg-teal-800 disabled:cursor-not-allowed text-slate-950 font-bold text-xs py-3 px-4 rounded shadow transition-all duration-200 uppercase tracking-wider"
        >
          {isScanning ? 'Scanning...' : 'Scan Page Tokens'}
        </button>

        {/* ADDED: Download button — only appears after scanning */}
        {hashScanned && tokens && (
          <button
            onClick={() => downloadConfig(tokens)}
            className="w-full bg-violet-600 hover:bg-violet-700 text-white font-bold text-xs py-3 px-4 rounded shadow transition-all duration-200 uppercase tracking-wider"
          >
            ↓ Download tailwind.config.js
          </button>
        )}
      </div>

    <div className="flex-1 overflow-y-auto px-5 pb-5 space-y-4">

      {/* Empty state — before first scan */}
                {!hashScanned && (
                    <div className="text-center text-xs text-slate-500 p-8 border border-dashed border-slate-800 rounded mt-4">
                        Click scan above to extract design tokens section by section
                    </div>
                )}

                {/* No colors found state */}
                {hashScanned && tokens && Object.keys(tokens.sections).length === 0 && (
                    <div className="text-center text-xs text-slate-500 p-8 border border-dashed border-slate-800 rounded mt-4">
                        No unique colors detected. Try a different page.
                    </div>
                )}
        

      {hashScanned && tokens && Object.keys(tokens.sections).length > 0 && (
        <div className="space-y-4 pt-2">

          {Object.entries(tokens.sections).map(([sectionName, colors]) => (
            <div key={sectionName} className="p-3 bg-slate-800 rounded border border-slate-700 space-y-2.5">

              {/* KEPT: Section header label */}
              <div className="flex items-center justify-between border-b border-slate-700/60 pb-1">
                <span className="text-[10px] font-bold text-teal-400 uppercase tracking-wider">
                  {sectionName}
                </span>
                <span className="text-[9px] bg-slate-950 px-1.5 py-0.5 rounded-full font-mono text-slate-400">
                  {colors.length} tokens
                </span>
              </div>
              <div className="grid grid-cols-3 gap-2">
                {colors.map((color) => (
                  <button
                    key={color}
                    onClick={() => handleColorCopy(color)}
                    className="flex flex-col items-center p-1.5 bg-slate-950 rounded border border-slate-900 space-y-1 hover:border-teal-500/50 transition-colors cursor-pointer w-full"
                  >
                    <div
                      className="w-full h-6 rounded"
                      style={{ backgroundColor: color }}
                    />
                    <code className="text-[9px] text-emerald-400 font-mono font-bold">
                      {copiedColor === color ? '✓ copied' : color}
                    </code>
                  </button>
                ))}
              </div>
            </div>
          ))}

          {Object.keys(tokens.cssVars).length > 0 && (
            <div className="p-3 bg-slate-800 rounded border border-slate-700 space-y-2">
              <span className="text-[10px] font-bold text-violet-400 uppercase tracking-wider block">
                CSS Variables (:root)
              </span>
              <div className="grid grid-cols-3 gap-2">
                {Object.entries(tokens.cssVars).slice(0, 9).map(([varName, val]) => (
                  <button
                    key={varName}
                    onClick={() => handleColorCopy(val)}
                    className="flex flex-col items-center p-1.5 bg-slate-950 rounded border border-slate-900 space-y-1 hover:border-violet-500/50 transition-colors w-full"
                  >
                    <div className="w-full h-6 rounded" style={{ backgroundColor: val }} />
                    <code className="text-[8px] text-violet-400 font-mono truncate w-full text-center">
                      {varName}
                    </code>
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

    </div>

     </div>
  );
}

  export default App ;
      
