import { useState } from 'react'
import './index.css';

// type SectionColors = Record<string, string[]>;
interface DesignTokens {
  sections: Record<string, string[]>;
  cssVars: Record<string, string>;
}


function generateTailwindConfig(tokens:DesignTokens):string {

  // Flattern all secion colors, duplicates
  const allColors = Object.values(tokens.sections)
  .flat()
  .filter((c, i, arr) => arr.indexOf(c) === i);

  // Build color enteries
     const colorLines = [
        ...allColors.map((hex, i) => `        'brand-${i + 1}': '${hex}'`),
        ...Object.entries(tokens.cssVars).map(
            ([varName, val]) => `        '${varName.replace('--', '')}': '${val}'`
        )
    ].join(',\n');

    return `/** @type {import('tailwindcss').Config} */
/** Auto-generated by Tailwind Config Extractor */
/** Source: ${window?.location?.hostname || 'unknown'} */

  module.exports ={
    theme: {
     extend:
       colors:{
        ${colorLines}

      } ,
       
      },
       
    },

    plugins: [],

  };
  `;

}

//  Download Config  - browser file download 

function downloadConfig(tokens: DesignTokens){
   const content = generateTailwindConfig(tokens);
   const blob = new  Blob([content], {type: 'text/javascript'});
   const url = URL.createObjectURL(blob);
   const a = document.createElement('a');
   a.href = url;
   a.download = 'tailwind.config.js';
   a.click();
   URL.revokeObjectURL(url);
}


function App() {

  const [sectiondColors, setSectionedColors] = useState<SectionColors>({});
  const [hashScanned, setHashScanned] = useState(false);

  const pingWebpageDom = async () => {
    // fetch the active Browser window tab identity
    const [activeTab] = await chrome.tabs.query({ active: true, currentWindow: true });

    if (!activeTab || !activeTab.id) {
      return;
    }

    chrome.tabs.sendMessage(activeTab.id, { action: "PING_DOM" }, (response) => {

      if (response && response.status === "success") {
        setSectionedColors(response.sections);
         setHashScanned(true);
      }
    });
  }

  return (
    <div className=" h-screen w-full p-5 bg-slate-900 text-slate-100 font-sans antialiased">
     
     {/* Header Section */}
      <div className="border-b border-slate-800 pb-2">
        <h1 className="text-xl font-bold text-teal-400">Tailwind Extractor</h1>
        <p className="text-[11px] text-slate-400">Phase 2 : Chrome Side Panel Mode</p>
      </div>

      {/* Control Action Button */}
      <button 
        onClick={pingWebpageDom} 
        className="w-full bg-teal-500 hover:bg-teal-600 text-slate-950 font-bold text-xs py-3 px-4 rounded shadow transition-all duration-200 cursor-pointer uppercase tracking-wider"
      >
        Scan Section Tokens
      </button>
     
      {/* The outer layout Dictionary loop */}
      {hashScanned && Object.keys(setSectionedColors).length > 0 && (
        <div className='space-y-4'>
          {Object.entries(sectiondColors).map(([sectionName, colors], sectionIdx) =>{
            return(
            <div key = {sectionIdx} className='p-3 bg-slate-800 rounded border border-slate-700 space-y-2.5'> 

            {/* Header Label for this specific webpage block section card */}
            <div className='flex items-center justify-between border-b border-slate-700/60 pb-1'>
              <span className='text-[10px] font-bold text-teal-400 uppercase tracking-wider'>{sectionName}</span>
              <span className="text-[9px] bg-slate-950 px-1.5 py-0.2 rounded-full font-mono text-slate-400">{colors.length}</span>
            </div>

            {/* The Ineer Color swatch Grid Array Loop */}
            <div className='grid grid-cols-3 gap-2'>
              {colors.map((color, colorIdx)=> (
                 <div key={colorIdx} className='flex flex-col items-center p-1.5 bg-slate-950 rounded border border-slate-900 space-y-1'>
                  <div className='w-full h-6 rounded' style={{backgroundColor: color}}/>
                   <code className="text-[9px] text-emerald-400 font-mono font-bold">{color}</code>
                 </div>
              ))}

            </div>
          
            </div>
          );
          })} 
        </div>
      )}

      {/* Fallback View state display message helper block */}
      {!hashScanned && (
        <div className="text-center text-xs text-slate-500 p-8 border border-dashed border-slate-800 rounded">
          Click the scan button above to analyze tokens section by section!
        </div>
      )}

    </div>
  )
}

export default App ;
{/* Header Section */}
      {/* <div className="mb-4 border-b border-slate-800 pb-2">
        <h1 className="text-xl font-bold text-teal-400">Tailwind Extracter</h1>
        <p className="">Phase 1 : Local Message Passing</p>
      </div> */}

      {/* Intractive Control Panel */}
      {/* <div className='space-y-4'>
        <button onClick={pingWebpageDom} className=' bg-teal-500 hover:bg-teal-600 text-slate-950 font-bold text-xs py-2.5 px-4 rounded shadow transition-all duration-200 cursor-pointer'>
          Ping webpage DOM
        </button> */}

        {/* Conitional Output Panel */}

        {/* {detectedColors.length > 0 && (
          <div className='p-3 bg-slate-800 rounded border border-slate-700 space-y-3'>
            <p className='text-[10px] font-semibold text-slate-400 uppercase tracking-wider'>
              Detected Design Tokens:
            </p>
            <div className='grid grid-cols-3 gap-2'>
              {detectedColors.map((color, index) => (
                <div key={index} className="flex flex-col items-center p-1.5 bg-slate-950 rounded border border-slate-800 space-y-1"> */}
                  {/* Live color Swatch Box */}
                  {/* <div className='w-full h-8 rounded border border-slate-600 shadow-inner'
                    style={{ backgroundColor: color }}
                  /> */}
                  {/* Raw String Output */}
                  {/* <code className='text-[10px] text-emerald-400 font-mono font-bold bg-slate-950 px-2 py-1 rounded border border-slate-800'>
                    {color}
                  </code>
                </div>
              ))}
            </div>
          </div>
        )}

      </div> */}